import "./globals.css"
import Nav from "./components/Nav"
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/pages/api/auth/[...nextauth]"
import Hydrate from "./components/Hydrate"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //Fetch the user
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className="mx-64">
        <Hydrate>
          <Nav user={session?.user} expires={session?.expires as string} />
          {children}
        </Hydrate>
      </body>
    </html>
  )
}
